### PR TITLE
fix #25 Prevent dropping empty values in template

### LINKED ISSUE #25: VM User Template: empty values are dropped in the new XML
I've lost some (empty) custom fields in our VMs testing pyone

`onevm show 345`
> X_TYPE=""

Then using pyone:
```
vm = one.vm.info(345)
print(vm.USER_TEMPLATE['X_TYPE'])
```
prints an empty string (there's no KeyError)
then I just update with the same dict
`one.vm.update(vm.ID, vm.USER_TEMPLATE)`
No issues, the templates gets updated.

But if I run again
```
vm = one.vm.info(345)
print(vm.USER_TEMPLATE['X_TYPE'])
```
Then I get a 
`KeyError: 'X_TYPE'`
Looking again at:
`onevm show 345`
There's no such field anymore.

As per https://pypi.org/project/dicttoxml/ 

> Items with a None type become empty XML elements.

I tried to add it back with 
```
vm = one.vm.info(345)
vm.USER_TEMPLATE['X_TYPE'] = None
one.vm.update(vm.ID, vm.USER_TEMPLATE)
```

With no luck.

Any suggestions?

Regards,
Germán.

### PR DESCRIPTION
**Pull request by xorel**
Although the pyone is currently being integrated to the OpenNebula/one repository, I opened this PR to eventually get some comment for the fix.

2 things:

1. In child2dict the xmltodict transforms empty xml elements to None value -- this should be fixed by none2emptystr        
                                                                      
2. When updating the template with empty xml element (like <X_TYPE></X_TYPE>) opennebula just drops that element (same for CLI). But sending <X_TYPE><![CDATA[]]></X_TYPE> works well -- this is what cdata=True in dicttoxml does.

### CODE REVIEW

**Comment by rvalle** [comment]
hi @xorel any idea why some tests are failing in travis?

**Comment by xorel** [comment]
I updated the fixtures signatures, not sure about the failing fedora.

**Comment by rvalle** [comment]
the fedora issue seems to be related to the test setup and not to the code itself.
it is not finding virtualenv

**Comment by rvalle** [comment]
@xorel is this issue still ongoing? I can see the travis tests started to fail on other distributions too.

**Comment by rvalle** [comment]
@xorel sorry, wrong repo...

**Pull request closed without merging**
